/**
 * AMPLIFY copy defaults — invitation flow, share copy, comparison view, insight block.
 */

import type { CopySection } from './types'

export function getAmplifyDefaults(): CopySection[] {
  return [
    // ── Accordion (mapa vivo) ──────────────────────────────────────
    {
      id: 'amplify.accordion.title',
      section: 'amplify',
      subsection: 'accordion',
      label: 'Título del acordeón',
      defaultValue: 'Comparar tu mapa',
      fieldType: 'short',
      hint: 'Título de la sección AMPLIFY en el mapa vivo.',
    },
    {
      id: 'amplify.accordion.description',
      section: 'amplify',
      subsection: 'accordion',
      label: 'Descripción del acordeón',
      defaultValue: '¿Crees que hacer este análisis puede ser de utilidad para tu pareja, un socio, un amigo?',
      fieldType: 'long',
    },
    {
      id: 'amplify.accordion.button',
      section: 'amplify',
      subsection: 'accordion',
      label: 'Botón de invitación',
      defaultValue: 'Envíale el link',
      fieldType: 'short',
    },
    {
      id: 'amplify.accordion.caption',
      section: 'amplify',
      subsection: 'accordion',
      label: 'Nota de confidencialidad',
      defaultValue: 'Su diagnóstico es confidencial. Solo se compara si ambos aceptáis.',
      fieldType: 'medium',
    },

    // ── Modal paso 1: Relación ─────────────────────────────────────
    {
      id: 'amplify.modal.step1.heading',
      section: 'amplify',
      subsection: 'modal',
      label: 'Paso 1 — Título',
      defaultValue: '¿Cuál es vuestra relación?',
      fieldType: 'short',
      hint: 'Primera pantalla del modal de invitación.',
    },
    {
      id: 'amplify.modal.step1.subtext',
      section: 'amplify',
      subsection: 'modal',
      label: 'Paso 1 — Subtexto',
      defaultValue: 'Esto nos ayuda a personalizar la comparación',
      fieldType: 'medium',
    },
    {
      id: 'amplify.modal.step1.rel_partner',
      section: 'amplify',
      subsection: 'modal',
      label: 'Relación — Pareja',
      defaultValue: 'Mi pareja',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step1.rel_business',
      section: 'amplify',
      subsection: 'modal',
      label: 'Relación — Socio/a',
      defaultValue: 'Mi socio/a',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step1.rel_friend',
      section: 'amplify',
      subsection: 'modal',
      label: 'Relación — Amigo/a',
      defaultValue: 'Un amigo/a',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step1.rel_other',
      section: 'amplify',
      subsection: 'modal',
      label: 'Relación — Otro',
      defaultValue: 'Otro',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step1.skip',
      section: 'amplify',
      subsection: 'modal',
      label: 'Paso 1 — Botón saltar',
      defaultValue: 'Saltar →',
      fieldType: 'short',
    },

    // ── Modal paso 2: Compartir ────────────────────────────────────
    {
      id: 'amplify.modal.step2.heading',
      section: 'amplify',
      subsection: 'modal',
      label: 'Paso 2 — Título',
      defaultValue: 'Comparte este link',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step2.subtext',
      section: 'amplify',
      subsection: 'modal',
      label: 'Paso 2 — Subtexto',
      defaultValue: 'Cuando complete su diagnóstico, ambos podréis ver la comparación.',
      fieldType: 'medium',
    },
    {
      id: 'amplify.modal.step2.copy_button',
      section: 'amplify',
      subsection: 'modal',
      label: 'Botón copiar',
      defaultValue: '📋 Copiar',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step2.copied',
      section: 'amplify',
      subsection: 'modal',
      label: 'Botón copiado',
      defaultValue: '¡Copiado!',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step2.whatsapp',
      section: 'amplify',
      subsection: 'modal',
      label: 'Botón WhatsApp',
      defaultValue: '📱 Enviar por WhatsApp',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step2.email',
      section: 'amplify',
      subsection: 'modal',
      label: 'Botón email',
      defaultValue: '✉️ Enviar por email',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step2.expiry',
      section: 'amplify',
      subsection: 'modal',
      label: 'Nota de caducidad',
      defaultValue: 'El link caduca en 30 días.',
      fieldType: 'short',
    },

    // ── Modal paso 3: Confirmación ─────────────────────────────────
    {
      id: 'amplify.modal.step3.heading',
      section: 'amplify',
      subsection: 'modal',
      label: 'Paso 3 — Título',
      defaultValue: 'Invitación lista',
      fieldType: 'short',
    },
    {
      id: 'amplify.modal.step3.confirmation',
      section: 'amplify',
      subsection: 'modal',
      label: 'Paso 3 — Texto confirmación',
      defaultValue: 'Cuando complete su diagnóstico, ambos recibiréis un email para ver la comparación.',
      fieldType: 'medium',
    },
    {
      id: 'amplify.modal.step3.close',
      section: 'amplify',
      subsection: 'modal',
      label: 'Paso 3 — Botón cerrar',
      defaultValue: 'Volver a mi mapa',
      fieldType: 'short',
    },

    // ── Share copy por perfil ──────────────────────────────────────
    // PC — Productivo Colapsado
    {
      id: 'amplify.share.pc.whatsapp',
      section: 'amplify',
      subsection: 'share',
      label: 'WhatsApp — Productivo Colapsado',
      defaultValue: 'He hecho un análisis de regulación nerviosa. Son 3 minutos y te da datos reales sobre sueño, energía y productividad. ¿Lo hacemos los dos y comparamos? {link}',
      fieldType: 'long',
      hint: '{link} se reemplaza automáticamente por el link de invitación.',
    },
    {
      id: 'amplify.share.pc.email_subject',
      section: 'amplify',
      subsection: 'share',
      label: 'Email asunto — Productivo Colapsado',
      defaultValue: 'Diagnóstico de productividad — ¿comparamos datos?',
      fieldType: 'medium',
    },
    {
      id: 'amplify.share.pc.email_body',
      section: 'amplify',
      subsection: 'share',
      label: 'Email cuerpo — Productivo Colapsado',
      defaultValue: 'He hecho un análisis de regulación nerviosa. Son 3 minutos y te da datos reales sobre sueño, energía y productividad.\n\n¿Lo hacemos los dos y comparamos?\n\n{link}',
      fieldType: 'long',
    },

    // FI — Fuerte Invisible
    {
      id: 'amplify.share.fi.whatsapp',
      section: 'amplify',
      subsection: 'share',
      label: 'WhatsApp — Fuerte Invisible',
      defaultValue: 'He encontrado un análisis de regulación nerviosa basado en datos. Sin narrativa, solo números. Si lo haces tú también podemos comparar métricas. 3 minutos: {link}',
      fieldType: 'long',
    },
    {
      id: 'amplify.share.fi.email_subject',
      section: 'amplify',
      subsection: 'share',
      label: 'Email asunto — Fuerte Invisible',
      defaultValue: 'Análisis de regulación — datos comparativos',
      fieldType: 'medium',
    },
    {
      id: 'amplify.share.fi.email_body',
      section: 'amplify',
      subsection: 'share',
      label: 'Email cuerpo — Fuerte Invisible',
      defaultValue: 'He encontrado un análisis de regulación nerviosa basado en datos. Sin narrativa, solo números.\n\nSi lo haces tú también, podemos comparar métricas. Son 3 minutos:\n\n{link}',
      fieldType: 'long',
    },

    // CE — Cuidador Exhausto
    {
      id: 'amplify.share.ce.whatsapp',
      section: 'amplify',
      subsection: 'share',
      label: 'WhatsApp — Cuidador Exhausto',
      defaultValue: 'He descubierto algo sobre regulación nerviosa que me ha ayudado. Si tú también lo haces, podemos ver cómo estamos los dos. Es confidencial y son 3 minutos: {link}',
      fieldType: 'long',
    },
    {
      id: 'amplify.share.ce.email_subject',
      section: 'amplify',
      subsection: 'share',
      label: 'Email asunto — Cuidador Exhausto',
      defaultValue: 'Algo que nos puede ayudar a los dos',
      fieldType: 'medium',
    },
    {
      id: 'amplify.share.ce.email_body',
      section: 'amplify',
      subsection: 'share',
      label: 'Email cuerpo — Cuidador Exhausto',
      defaultValue: 'He descubierto algo sobre regulación nerviosa que me ha ayudado a entender mejor cómo estoy.\n\nSi tú también lo haces, podemos ver cómo estamos los dos. Es confidencial y son 3 minutos:\n\n{link}',
      fieldType: 'long',
    },

    // CP — Controlador Paralizado
    {
      id: 'amplify.share.cp.whatsapp',
      section: 'amplify',
      subsection: 'share',
      label: 'WhatsApp — Controlador Paralizado',
      defaultValue: 'He hecho un diagnóstico estructurado de 5 dimensiones de regulación nerviosa. Si lo haces tú, comparamos resultados con un plan de seguimiento. 3 minutos: {link}',
      fieldType: 'long',
    },
    {
      id: 'amplify.share.cp.email_subject',
      section: 'amplify',
      subsection: 'share',
      label: 'Email asunto — Controlador Paralizado',
      defaultValue: 'Plan de regulación comparativa — ¿te apuntas?',
      fieldType: 'medium',
    },
    {
      id: 'amplify.share.cp.email_body',
      section: 'amplify',
      subsection: 'share',
      label: 'Email cuerpo — Controlador Paralizado',
      defaultValue: 'He hecho un diagnóstico estructurado de 5 dimensiones de regulación nerviosa.\n\nSi lo haces tú, podemos comparar resultados con un plan de seguimiento. Son 3 minutos:\n\n{link}',
      fieldType: 'long',
    },

    // Default
    {
      id: 'amplify.share.default.whatsapp',
      section: 'amplify',
      subsection: 'share',
      label: 'WhatsApp — Por defecto',
      defaultValue: 'He hecho un diagnóstico de regulación nerviosa y me gustaría que lo hicieras tú también para poder comparar nuestros resultados. Son 3 minutos: {link}',
      fieldType: 'long',
    },
    {
      id: 'amplify.share.default.email_subject',
      section: 'amplify',
      subsection: 'share',
      label: 'Email asunto — Por defecto',
      defaultValue: 'Diagnóstico de regulación — ¿comparamos?',
      fieldType: 'medium',
    },
    {
      id: 'amplify.share.default.email_body',
      section: 'amplify',
      subsection: 'share',
      label: 'Email cuerpo — Por defecto',
      defaultValue: 'He hecho un diagnóstico de regulación nerviosa y me gustaría que lo hicieras tú también para poder comparar nuestros resultados.\n\nSon 3 minutos:\n\n{link}',
      fieldType: 'long',
    },

    // ── Comparación — Vista ────────────────────────────────────────
    {
      id: 'amplify.comparison.header',
      section: 'amplify',
      subsection: 'comparison',
      label: 'Título de la comparación',
      defaultValue: 'Tu comparación de regulación',
      fieldType: 'short',
    },
    {
      id: 'amplify.comparison.you_label',
      section: 'amplify',
      subsection: 'comparison',
      label: 'Etiqueta "Tú"',
      defaultValue: 'Tú',
      fieldType: 'short',
    },
    {
      id: 'amplify.comparison.back',
      section: 'amplify',
      subsection: 'comparison',
      label: 'Link volver',
      defaultValue: 'Volver a mi mapa',
      fieldType: 'short',
    },
    {
      id: 'amplify.comparison.footer',
      section: 'amplify',
      subsection: 'comparison',
      label: 'Nota de confidencialidad',
      defaultValue: 'Confidencial. Solo vosotros dos podéis ver esta comparación.',
      fieldType: 'medium',
    },

    // ── Insight block (CTA) ────────────────────────────────────────
    {
      id: 'amplify.insight.heading',
      section: 'amplify',
      subsection: 'insight',
      label: 'Título del insight',
      defaultValue: 'Lo que revelan los dos mapas juntos',
      fieldType: 'short',
      hint: 'Bloque de conversión al final de la comparación.',
    },
    {
      id: 'amplify.insight.tagline',
      section: 'amplify',
      subsection: 'insight',
      label: 'Tagline (cursiva)',
      defaultValue: 'Lo que ningún diagnóstico individual puede revelar, dos mapas juntos sí.',
      fieldType: 'medium',
    },
    {
      id: 'amplify.insight.body',
      section: 'amplify',
      subsection: 'insight',
      label: 'Texto del insight',
      defaultValue: 'Si uno de los dos se regula, el otro lo nota. Si los dos os reguláis, todo cambia.',
      fieldType: 'medium',
    },
    {
      id: 'amplify.insight.cta',
      section: 'amplify',
      subsection: 'insight',
      label: 'Botón CTA',
      defaultValue: 'Empezar la Semana 1 — 97€',
      fieldType: 'short',
    },
    {
      id: 'amplify.insight.caption',
      section: 'amplify',
      subsection: 'insight',
      label: 'Nota bajo CTA',
      defaultValue: 'Cada programa es individual y personalizado.',
      fieldType: 'medium',
    },
  ]
}
