/**
 * Mapa Vivo copy defaults.
 * Extracted from: FocusBanner, EvolutionTimeline, EvolutionSession,
 * AspiracionalTimeline, LeadDimensions.
 */

import type { CopySection } from './types'

export function getMapaDefaults(): CopySection[] {
  return [
    // ── FOCUS BANNER — NEW states ────────────────────────────────────
    {
      id: 'mapa.focus.new.archetype.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Mecanismo de defensa nuevo (tag)',
      defaultValue: 'NUEVO DESDE TU ÚLTIMA VISITA',
      fieldType: 'short',
      hint: 'Tag que aparece cuando el mecanismo de defensa se desbloquea por primera vez.',
    },
    {
      id: 'mapa.focus.new.archetype.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Mecanismo de defensa nuevo (CTA)',
      defaultValue: 'Descubrir tu mecanismo de defensa completo',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.insightD7.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Insight D7 nuevo (tag)',
      defaultValue: 'TU MAPA SE HA ACTUALIZADO',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.insightD7.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Insight D7 nuevo (CTA)',
      defaultValue: 'Ver tu evaluación completa',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.session.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión nueva (tag)',
      defaultValue: 'TU SIGUIENTE PASO',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.session.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Programa (título)',
      defaultValue: 'Empieza la Semana 1 del Programa de neuroregulación L.A.R.S.©',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.session.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Programa (descripción)',
      defaultValue: 'Un entrenamiento de Liderazgo de Alto Rendimiento Sostenible de 12 semanas liderado por médicos y psicoterapeutas. Los primeros cambios llegan en menos de 72h. con el incremento sustancial en tu descanso.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.new.session.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Programa (CTA)',
      defaultValue: 'Los detalles',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.subdimensions.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Subdimensiones nuevas (tag)',
      defaultValue: 'PROFUNDIZA TU EVALUACIÓN',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.subdimensions.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Subdimensiones nuevas (CTA)',
      defaultValue: 'Responder ahora',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.book.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Libro nuevo (tag)',
      defaultValue: 'PARA TI',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.book.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Libro nuevo (título)',
      defaultValue: 'Un capítulo escrito para tu patrón',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.book.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Libro nuevo (CTA)',
      defaultValue: 'Leer extracto',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.reevaluation.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación nueva (título)',
      defaultValue: '¿Ha cambiado algo en tu regulación?',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.new.reevaluation.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación nueva (descripción)',
      defaultValue: 'Responde las mismas 10 preguntas y compara con tu día 0.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.new.reevaluation.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación nueva (CTA)',
      defaultValue: 'Reevaluar mi estado',
      fieldType: 'short',
    },

    // ── FOCUS BANNER — PENDING states ────────────────────────────────
    {
      id: 'mapa.focus.pending.session.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión pendiente (tag)',
      defaultValue: 'PENDIENTE',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.session.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión pendiente (título)',
      defaultValue: 'Tu sesión con Javier',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.session.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Sesión pendiente (descripción)',
      defaultValue: 'Aún no has reservado tu sesión gratuita de 30 minutos. Javier ya tiene tu mapa.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.pending.subdimensions.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Subdimensiones pendientes (tag)',
      defaultValue: 'PENDIENTE',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.subdimensions.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Subdimensiones pendientes (título)',
      defaultValue: 'Profundiza tu evaluación',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.reevaluation.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación disponible (tag)',
      defaultValue: 'DISPONIBLE',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.reevaluation.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación disponible (título)',
      defaultValue: 'Tu reevaluación está lista',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.pending.reevaluation.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Reevaluación disponible (descripción)',
      defaultValue: 'Compara tu estado actual con tu día 0. Verás cuánto ha cambiado.',
      fieldType: 'medium',
    },

    // ── FOCUS BANNER — TEASER (no pagado) ────────────────────────────
    {
      id: 'mapa.focus.teaser.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Teaser no pagado (tag)',
      defaultValue: 'TU SIGUIENTE PASO',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.teaser.title',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Teaser no pagado (título)',
      defaultValue: 'Tu regulación es un proceso de 12 semanas',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.teaser.description',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Teaser no pagado (descripción)',
      defaultValue: 'Los primeros cambios llegan en 72 horas. Tu primer paso son los próximos 7 días.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.teaser.cta',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Teaser no pagado (CTA)',
      defaultValue: 'Ver tu camino',
      fieldType: 'short',
    },

    // ── FOCUS BANNER — DEFAULT ───────────────────────────────────────
    {
      id: 'mapa.focus.default.tag',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Por defecto (tag)',
      defaultValue: 'TU MAPA EVOLUCIONA',
      fieldType: 'short',
    },
    {
      id: 'mapa.focus.default.description.waiting',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Por defecto (esperando desbloqueo)',
      defaultValue: 'Cada semana aparece algo nuevo. Vuelve cuando quieras.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.focus.default.description.complete',
      section: 'mapa',
      subsection: 'focus',
      label: 'Focus — Todo desbloqueado',
      defaultValue: 'Todas las secciones están desbloqueadas. Explora tu mapa completo.',
      fieldType: 'medium',
    },

    // ── EVOLUTION TIMELINE — Milestones ──────────────────────────────
    {
      id: 'mapa.evolution.header',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Encabezado',
      defaultValue: 'Tu mapa evoluciona',
      fieldType: 'short',
      hint: 'Texto que encabeza la línea temporal vertical del mapa.',
    },
    {
      id: 'mapa.evolution.d0.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 0 label',
      defaultValue: 'Tu análisis',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d0.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 0 sublabel',
      defaultValue: '5 dimensiones · Score global',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d3.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 3 label',
      defaultValue: 'Mecanismo de defensa',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d3.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 3 sublabel',
      defaultValue: '7 tipos · Tu patrón profundo',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d7.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 7 label',
      defaultValue: 'Insight colectivo',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d7.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 7 sublabel',
      defaultValue: 'Dato nuevo en tu peor dimensión',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d10.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 10 label',
      defaultValue: 'Sesión con Javier',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d10.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 10 sublabel',
      defaultValue: '20 min gratuitos · Sin compromiso',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d14.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 14 label',
      defaultValue: 'Subdimensiones',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d14.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 14 sublabel',
      defaultValue: '2 preguntas · Mayor resolución',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d21.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 21 label',
      defaultValue: 'Extracto del libro',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d21.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 21 sublabel',
      defaultValue: 'Capítulo personalizado',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d30.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 30 label',
      defaultValue: 'Reevaluación',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d30.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 30 sublabel',
      defaultValue: 'Compara con tu día 0',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d90.label',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 90 label',
      defaultValue: 'Trimestral',
      fieldType: 'short',
    },
    {
      id: 'mapa.evolution.d90.sublabel',
      section: 'mapa',
      subsection: 'evolution',
      label: 'Timeline — Día 90 sublabel',
      defaultValue: 'Evolución a largo plazo',
      fieldType: 'short',
    },

    // ── SESSION ──────────────────────────────────────────────────────
    {
      id: 'mapa.session.title',
      section: 'mapa',
      subsection: 'session',
      label: 'Sesión — título',
      defaultValue: '¿Quieres que el director del programa revise tu mapa contigo?',
      fieldType: 'short',
      hint: 'Título de la sección de reserva de sesión en el mapa.',
    },
    {
      id: 'mapa.session.description',
      section: 'mapa',
      subsection: 'session',
      label: 'Sesión — descripción',
      defaultValue: '30 minutos. Sin compromiso. Ya tiene tus datos — no repites nada.',
      fieldType: 'medium',
    },

    // ── DIMENSIONS ───────────────────────────────────────────────────
    {
      id: 'mapa.dimension.d1',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 1 — Regulación',
      defaultValue: 'Regulación',
      fieldType: 'short',
      hint: 'Nombre de la primera dimensión. Aparece en el mapa y en emails.',
    },
    {
      id: 'mapa.dimension.d2',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 2 — Sueño',
      defaultValue: 'Sueño',
      fieldType: 'short',
    },
    {
      id: 'mapa.dimension.d3',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 3 — Claridad',
      defaultValue: 'Claridad',
      fieldType: 'short',
    },
    {
      id: 'mapa.dimension.d4',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 4 — Emocional',
      defaultValue: 'Emocional',
      fieldType: 'short',
    },
    {
      id: 'mapa.dimension.d5',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión 5 — Alegría',
      defaultValue: 'Alegría',
      fieldType: 'short',
    },

    // ── DIMENSIONS — Tags ─────────────────────────────────────────────
    {
      id: 'mapa.dimension.priority',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión — etiqueta de prioridad',
      defaultValue: 'Tu prioridad nº1',
      fieldType: 'short',
      hint: 'Tag que aparece en la dimensión más comprometida.',
    },
    {
      id: 'mapa.dimension.improvable72h',
      section: 'mapa',
      subsection: 'dimensions',
      label: 'Dimensión Sueño — etiqueta de mejora',
      defaultValue: 'Mejorable en 72 horas',
      fieldType: 'short',
      hint: 'Tag específico para la dimensión de Sueño.',
    },

    // ── ASPIRACIONAL — 3 fases ───────────────────────────────────────
    {
      id: 'mapa.aspiracional.headline1',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Aspiracional — titular línea 1',
      defaultValue: 'Empieza la Semana 1 del Programa de neuroregulación L.A.R.S.©',
      fieldType: 'short',
      hint: 'Primera línea del titular de la Zona 4 del mapa.',
    },
    {
      id: 'mapa.aspiracional.headline2',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Aspiracional — titular línea 2',
      defaultValue: 'Un entrenamiento de Liderazgo de Alto Rendimiento Sostenible de 12 semanas liderado por médicos y psicoterapeutas. Los primeros cambios llegan en menos de 72h. con el incremento sustancial en tu descanso.',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase1.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 1 — título',
      defaultValue: 'Fase 1: El Despertar',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase1.subtitle',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 1 — subtítulo',
      defaultValue: 'Semanas 1-4- ▪ Reconocer y estabilizar.',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase1.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 1 — descripción',
      defaultValue: 'Entenderás qué le pasa a tu biología: neurotransmisores, función hormonal, inflamación. Restaurarás tu sueño con un protocolo diseñado por un médico. En la semana 4, tu primer balance formal confirmará lo que tu cuerpo ya empieza a notar.',
      fieldType: 'long',
    },
    {
      id: 'mapa.aspiracional.fase2.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 2 — título',
      defaultValue: 'Fase 2: La Metamorfosis',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase2.subtitle',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 2 — subtítulo',
      defaultValue: 'Semanas 5-8- ▪ Activar y procesar.',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase2.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 2 — descripción',
      defaultValue: 'Desmontarás las creencias y patrones que sostienen el ciclo. Conocerás las partes internas que dirigen tus decisiones sin que lo sepas — el perfeccionista, el controlador, el crítico — y aprenderás a liderarlas. Lo que el burnout congeló empieza a procesarse.',
      fieldType: 'long',
    },
    {
      id: 'mapa.aspiracional.fase3.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 3 — título',
      defaultValue: 'Fase 3: El liderazgo sostenible',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase3.subtitle',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 3 — subtítulo',
      defaultValue: 'Semanas 9-12- ▪ Conectar y reconstruir.',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.fase3.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Fase 3 — descripción',
      defaultValue: 'Repararás los vínculos que el burnout dañó, pondrás límites desde tus valores y diseñarás tu nueva arquitectura vital. Un sistema de alertas tempranas para que el burnout no vuelva.',
      fieldType: 'long',
    },

    // ── PROGRAMA — Semanas detalladas por fase ──────────────────────
    // FASE 1: EL DESPERTAR (Semanas 1–4)
    {
      id: 'mapa.programa.fase1.week1.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — Semana 1 título',
      defaultValue: 'RECONOCER',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase1.week1.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — Semana 1 descripción',
      defaultValue: 'El burnout como exilio y mensajero',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase1.week2.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — Semana 2 título',
      defaultValue: 'ESTABILIZAR',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase1.week2.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — Semana 2 descripción',
      defaultValue: 'Regulación, sueño y las primeras partes',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase1.week3.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — Semana 3 título',
      defaultValue: 'NUTRIR',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase1.week3.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — Semana 3 descripción',
      defaultValue: 'Bioquímica, detox y los patrones que ignoran al cuerpo',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase1.week4.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — Semana 4 título',
      defaultValue: 'ACTIVAR',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase1.week4.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — Semana 4 descripción',
      defaultValue: 'Las cuatro funciones comprometidas y la neuroplasticidad',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase1.results',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — resultados',
      defaultValue: 'Duermes mejor, tienes más claridad, más energía, y tu cuerpo empieza a responder. Tienes un mapa completo de tus patrones de burnout, entiendes qué funciones cerebrales necesitan reparación y métricas objetivas de tu punto de partida.',
      fieldType: 'long',
    },
    {
      id: 'mapa.programa.fase1.metrics',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — métricas',
      defaultValue: 'Sueño +15-30%. Energía matutina restaurada. Métricas base completas.',
      fieldType: 'medium',
    },

    // FASE 2: LA METAMORFOSIS (Semanas 5–8)
    {
      id: 'mapa.programa.fase2.week5.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — Semana 5 título',
      defaultValue: 'NARRATIVAS',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase2.week5.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — Semana 5 descripción',
      defaultValue: 'La Madre Sobreprotectora, las creencias limitantes y la defusión',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase2.week6.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — Semana 6 título',
      defaultValue: 'ASAMBLEA INTERIOR',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase2.week6.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — Semana 6 descripción',
      defaultValue: 'Sombra, partes, protectores y exiliados',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase2.week7.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — Semana 7 título',
      defaultValue: 'PROCESAR',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase2.week7.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — Semana 7 descripción',
      defaultValue: 'Duelos, irrupciones emocionales y las bestias internas',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase2.week8.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — Semana 8 título',
      defaultValue: 'INTEGRAR',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase2.week8.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — Semana 8 descripción',
      defaultValue: 'Ventana de tolerancia, ACT, autocompasión y cierre',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase2.results',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — resultados',
      defaultValue: 'Has desmontado los patrones mentales que te trajeron al burnout, has procesado las emociones congeladas y tienes una relación radicalmente diferente con tus pensamientos, tus partes internas y tus miedos.',
      fieldType: 'long',
    },
    {
      id: 'mapa.programa.fase2.metrics',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — métricas',
      defaultValue: 'MBI baja 20-30%. Niebla mental reducida. Capacidad de decisión restaurada.',
      fieldType: 'medium',
    },

    // FASE 3: EL LÍDER FÉNIX (Semanas 9–12)
    {
      id: 'mapa.programa.fase3.week9.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — Semana 9 título',
      defaultValue: 'CONECTAR',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase3.week9.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — Semana 9 descripción',
      defaultValue: 'Relaciones, corregulación, límites y reparación',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase3.week10.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — Semana 10 título',
      defaultValue: 'VALORES',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase3.week10.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — Semana 10 descripción',
      defaultValue: 'Brújula, acción comprometida y laboratorio de valentía',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase3.week11.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — Semana 11 título',
      defaultValue: 'RECONCILIACIÓN',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase3.week11.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — Semana 11 descripción',
      defaultValue: 'Liberación, nueva narrativa e identidad',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase3.week12.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — Semana 12 título',
      defaultValue: 'RECONSTRUIR',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.fase3.week12.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — Semana 12 descripción',
      defaultValue: 'La nueva arquitectura y el regreso a casa',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase3.results',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — resultados',
      defaultValue: 'Tienes una arquitectura vital sostenible, sistemas de alertas tempranas, relaciones reparadas y la capacidad de liderar tu vida sin que el precio sea tu salud. El burnout se convierte en tu maestro, no en tu carcelero.',
      fieldType: 'long',
    },
    {
      id: 'mapa.programa.fase3.metrics',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — métricas',
      defaultValue: 'Rendimiento sostenible. Claridad restaurada. Confianza real.',
      fieldType: 'medium',
    },

    // ── PROGRAMA — Fase intro texts ──────────────────────────────────
    {
      id: 'mapa.programa.fase1.intro',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 1 — intro',
      defaultValue: 'Tu biología se empieza a normalizar.',
      fieldType: 'medium',
      hint: 'Frase en itálica bajo el título de la fase.',
    },
    {
      id: 'mapa.programa.fase2.intro',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 2 — intro',
      defaultValue: 'Tu cabeza se reorganiza y lo que estaba congelado se procesa.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.fase3.intro',
      section: 'mapa',
      subsection: 'programa',
      label: 'Fase 3 — intro',
      defaultValue: 'Tus relaciones se reparan y construyes una nueva arquitectura vital.',
      fieldType: 'medium',
    },

    // ── SEMANA 1 DETALLE — Presentaciones del Dr. Carlos Alvear ─────
    {
      id: 'mapa.programa.week1.presentations.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 detalle — título presentaciones',
      defaultValue: 'Presentaciones del Dr. Carlos Alvear L.',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.week1.pres1',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — Presentación 1',
      defaultValue: 'Psiconeurobiología y epigenética del burnout (15 min.)',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.week1.pres2',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — Presentación 2',
      defaultValue: 'Los siete patrones que llevan al burnout (15 min.) + Las métricas y los hitos de la regulación (15 min.)',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.week1.pres3',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — Presentación 3',
      defaultValue: 'El potencial de crecimiento como líder y como individuo (15 min.)',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.week1.learning.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — título "Qué vas a aprender"',
      defaultValue: 'Qué vas a aprender',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.week1.learning.items',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — items de aprendizaje',
      defaultValue: 'Neurociencia real de tu agotamiento mental. · Cartografía corporal del agotamiento. · Los 7 patrones de burnout profesional. · Métricas base: MBI e indicadores biológicos. · Primera práctica de regulación vagal.',
      fieldType: 'long',
      hint: 'Separados por " · " (punto medio con espacios). Cada item debe terminar con punto.',
    },
    {
      id: 'mapa.programa.week1.sleep.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — Protocolo Sueño título',
      defaultValue: 'Protocolo de Sueño de Emergencia',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.week1.sleep.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — Protocolo Sueño descripción',
      defaultValue: 'Diseñado por el Dr. Carlos Alvear. Un plan concreto para ganar hasta una hora más de sueño al día. Resultados en 72 horas.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.programa.week1.mnn.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — MNN título',
      defaultValue: 'Mapa de Niveles de Neurotransmisores (MNN©)',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.week1.mnn.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — MNN descripción',
      defaultValue: 'Análisis de tu perfil de neurotransmisión y las deficiencias en este momento de dopamina, GABA, serotonina y acetilcolina. Plan personalizado de neuroregulación.',
      fieldType: 'long',
    },
    {
      id: 'mapa.programa.week1.session.title',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — Sesión título',
      defaultValue: 'Sesión 1:1 con Javier A. Martín Ramos',
      fieldType: 'short',
    },
    {
      id: 'mapa.programa.week1.session.description',
      section: 'mapa',
      subsection: 'programa',
      label: 'Semana 1 — Sesión descripción',
      defaultValue: 'Director del programa. Ya tiene tu mapa — la sesión arranca desde tus datos, no desde cero.',
      fieldType: 'medium',
    },

    // ── SESIÓN CTA (disponible desde día 0) ─────────────────────────
    {
      id: 'mapa.sessionCta.title',
      section: 'mapa',
      subsection: 'sessionCta',
      label: 'Sesión CTA — título',
      defaultValue: 'Reserva tu sesión de asesoramiento con el Director del Programa',
      fieldType: 'short',
      hint: 'CTA de sesión visible desde el primer momento en el mapa.',
    },
    {
      id: 'mapa.sessionCta.subtitle',
      section: 'mapa',
      subsection: 'sessionCta',
      label: 'Sesión CTA — subtítulo',
      defaultValue: 'Ya tiene tu mapa — no tendrás que repetirte. No tienes nada que perder.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.sessionCta.badge',
      section: 'mapa',
      subsection: 'sessionCta',
      label: 'Sesión CTA — badge',
      defaultValue: '20min.',
      fieldType: 'short',
    },
    {
      id: 'mapa.sessionCta.button',
      section: 'mapa',
      subsection: 'sessionCta',
      label: 'Sesión CTA — botón',
      defaultValue: 'Elegir horario',
      fieldType: 'short',
    },
    {
      id: 'mapa.sessionCta.booked.title',
      section: 'mapa',
      subsection: 'sessionCta',
      label: 'Sesión CTA — título cuando reservada',
      defaultValue: 'Tu sesión está confirmada',
      fieldType: 'short',
    },

    // ── EXTRACTO PDF — Descarga ─────────────────────────────────────
    {
      id: 'mapa.bookDownload.title',
      section: 'mapa',
      subsection: 'bookDownload',
      label: 'Extracto PDF — título',
      defaultValue: 'Descarga el primer capítulo',
      fieldType: 'short',
      hint: 'Solo se muestra si hay un PDF subido desde el admin.',
    },
    {
      id: 'mapa.bookDownload.description',
      section: 'mapa',
      subsection: 'bookDownload',
      label: 'Extracto PDF — descripción',
      defaultValue: 'Introducción y Capítulo 1 del libro del Dr. Carlos Alvear. La ciencia detrás de tu regulación.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.bookDownload.button',
      section: 'mapa',
      subsection: 'bookDownload',
      label: 'Extracto PDF — botón de descarga',
      defaultValue: 'Descargar extracto',
      fieldType: 'short',
    },

    {
      id: 'mapa.aspiracional.mapNote',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Nota de evolución del mapa',
      defaultValue: 'Tu mapa también evoluciona: cada semana aparece algo nuevo — tu perfil profundo, insights colectivos, reevaluaciones. Vuelve cuando quieras.',
      fieldType: 'medium',
    },

    // ── ASPIRACIONAL — Semana 1 items ────────────────────────────────
    {
      id: 'mapa.aspiracional.week1.item1.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Protocolo de Sueño',
      defaultValue: 'Protocolo de Sueño de Emergencia',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.week1.item1.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Protocolo de Sueño (descripción)',
      defaultValue: 'Diseñado por el Dr. Carlos Alvear. Un plan concreto para ganar hasta una hora más de sueño al día. Resultados en 72 horas.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.aspiracional.week1.item2.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Sesión 1:1',
      defaultValue: 'Sesión 1:1 con Javier A. Martín Ramos',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.week1.item2.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Sesión 1:1 (descripción)',
      defaultValue: 'Reunión orientación con el Director del programa para evaluar resultados y próximos pasos.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.aspiracional.week1.item3.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — MNN©',
      defaultValue: 'Mapa de Niveles de Neurotransmisores (MNN©)',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.week1.item3.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — MNN© (descripción)',
      defaultValue: 'Análisis de tu perfil de neurotransmisión y las deficiencias en este momento de dopamina, GABA, serotonina y acetilcolina. Plan personalizado de neuroregulación.',
      fieldType: 'long',
    },
    {
      id: 'mapa.aspiracional.week1.item4.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Garantía',
      defaultValue: 'Garantía total',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.week1.item4.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — Garantía (descripción)',
      defaultValue: '7 días. Si no notas mejora en tu sueño, devolución íntegra. Sin preguntas. Sin formularios.',
      fieldType: 'medium',
    },

    // ── ASPIRACIONAL — Post-pago & Checkout ────────────────────────────
    {
      id: 'mapa.aspiracional.hasPaid.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Post-pago — título',
      defaultValue: 'Tu Semana 1 está en marcha.',
      fieldType: 'short',
      hint: 'Texto que aparece después de completar el pago.',
    },
    {
      id: 'mapa.aspiracional.hasPaid.description',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Post-pago — descripción',
      defaultValue: 'Revisa tu email para el Protocolo de Sueño de Emergencia.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.aspiracional.week1.accordion.title',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Semana 1 — título del acordeón',
      defaultValue: '¿Qué incluye la Semana 1?',
      fieldType: 'short',
      hint: 'Título del desplegable que muestra el contenido de la Semana 1.',
    },
    {
      id: 'mapa.aspiracional.checkout.loading',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Checkout — botón cargando',
      defaultValue: 'Redirigiendo…',
      fieldType: 'short',
      hint: 'Texto del botón mientras se procesa el pago.',
    },
    {
      id: 'mapa.aspiracional.checkout.error',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Checkout — mensaje de error',
      defaultValue: 'No se pudo conectar con el sistema de pago. Tus datos están a salvo.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.aspiracional.checkout.retry',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Checkout — botón reintentar',
      defaultValue: 'Intentar de nuevo',
      fieldType: 'short',
    },

    // ── ASPIRACIONAL — CTA ───────────────────────────────────────────
    {
      id: 'mapa.aspiracional.preCta',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Pre-CTA — frase emocional',
      defaultValue: 'Has sobrevivido a todo. Ahora tu cuerpo te pide a gritos que empieces a vivir de verdad.',
      fieldType: 'medium',
      hint: 'Frase en cursiva antes del botón de compra. Voz de Javier.',
    },
    {
      id: 'mapa.aspiracional.delta',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Delta — texto de 72 horas',
      defaultValue: 'Los primeros cambios llegan en 72 horas. No en meses — en 3 días. El Protocolo de rescate del sueño es el primer paso hacia un profundo crecimiento físico y mental.',
      fieldType: 'long',
    },
    {
      id: 'mapa.aspiracional.ctaButton',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Botón CTA',
      defaultValue: 'Empieza la Semana 1 por 97€',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.priceCopy',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Sub-copy de precio',
      defaultValue: '',
      fieldType: 'medium',
    },
    {
      id: 'mapa.aspiracional.guarantee',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Garantía bajo el precio',
      defaultValue: 'Si tu sueño no mejora en 7 días, te devolvemos los 97€.',
      fieldType: 'short',
    },
    {
      id: 'mapa.aspiracional.reencuadre',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Reencuadre de precio',
      defaultValue: 'El programa completo tiene tres niveles de acompañamiento desde 1.500€ (financiables), según la profundidad que necesites. La elección del plan viene después — cuando hayas comprobado con tu propio cuerpo que esto funciona.',
      fieldType: 'long',
      hint: 'Texto que contextualiza el precio de 97€ vs el programa completo.',
    },
    {
      id: 'mapa.aspiracional.reencuadre2',
      section: 'mapa',
      subsection: 'aspiracional',
      label: 'Reencuadre — cierre',
      defaultValue: 'Por eso existe la Semana 1.',
      fieldType: 'short',
    },

    // ── MÓDULO DE DESBLOQUEOS PROGRESIVOS ────────────────────────────
    {
      id: 'mapa.unlock.title',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos progresivos — título',
      defaultValue: 'Se desbloquea en los próximos días',
      fieldType: 'short',
      hint: 'Encabezado del módulo de desbloqueos.',
    },
    {
      id: 'mapa.unlock.mechanism.title',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Mecanismo de defensa (título)',
      defaultValue: 'Mecanismos de defensa adaptativos',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.mechanism.subtitle',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Mecanismo de defensa (subtítulo)',
      defaultValue: 'Obsesión',
      fieldType: 'short',
      hint: 'Se reemplaza dinámicamente con el nombre del mecanismo del usuario.',
    },
    {
      id: 'mapa.unlock.session.title',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Llamada de asesoramiento (título)',
      defaultValue: 'Llamada gratuita de asesoramiento',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.session.subtitle',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Llamada de asesoramiento (subtítulo)',
      defaultValue: '20min',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.compare.title',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Recomendar este mapa (título)',
      defaultValue: 'Recomendar este mapa',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.compare.subtitle',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Recomendar este mapa (subtítulo)',
      defaultValue: 'Invita a alguien',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.fearsNeeds.title',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Miedos + necesidades (título)',
      defaultValue: 'Tus miedos + necesidades',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.fearsNeeds.subtitle',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Miedos + necesidades (subtítulo)',
      defaultValue: 'Miedos principales · 3 capas de necesidad · Patrones de burnout',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.priority.title',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Profundizamos en tu prioridad (título)',
      defaultValue: 'Profundizamos en tu prioridad nº1',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.bookExcerpt.title',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Extracto del libro (título)',
      defaultValue: 'Extracto del libro',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.evolution.title',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — Tu Evolución (título)',
      defaultValue: 'Tu Evolución',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.badge.pending',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — badge pendiente',
      defaultValue: 'PENDIENTE',
      fieldType: 'short',
      hint: 'Badge en color dorado para estados pendientes.',
    },
    {
      id: 'mapa.unlock.today',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — disponible hoy',
      defaultValue: 'Disponible hoy',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.tomorrow',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — disponible mañana',
      defaultValue: 'Disponible mañana',
      fieldType: 'short',
    },
    {
      id: 'mapa.unlock.daysUntil',
      section: 'mapa',
      subsection: 'unlock',
      label: 'Desbloqueos — disponible en X días',
      defaultValue: 'Disponible en {days} días',
      fieldType: 'short',
      hint: 'Usa {days} como placeholder para el número de días.',
    },

    // ══════════════════════════════════════════════════════════════════════
    // SUBDIMENSIONES — Preguntas de profundización (Día 3)
    // 5 dimensiones × (1 intro + 2 preguntas × 4 opciones) = 55 entradas
    // ══════════════════════════════════════════════════════════════════════

    // ── D1: Regulación Nerviosa ──────────────────────────────────────────
    {
      id: 'mapa.subdim.d1.intro',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — intro',
      defaultValue: 'Tu regulación nerviosa tiene 3 subdimensiones que no pudimos calcular con tu análisis original:',
      fieldType: 'medium',
      hint: 'Texto introductorio antes de las preguntas de Regulación Nerviosa.',
    },
    {
      id: 'mapa.subdim.d1.q1.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — Pregunta 1',
      defaultValue: 'Cuando terminas tu jornada laboral, ¿cuánto tiempo tardas en "desconectar" mentalmente?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Activación diurna.',
    },
    {
      id: 'mapa.subdim.d1.q1.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — P1 opción A',
      defaultValue: 'No desconecto — sigo pensando en el trabajo hasta dormirme.',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d1.q1.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — P1 opción B',
      defaultValue: '2-3 horas, pero con esfuerzo consciente.',
      fieldType: 'short',
    },
    {
      id: 'mapa.subdim.d1.q1.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — P1 opción C',
      defaultValue: 'Unos 30-60 minutos.',
      fieldType: 'short',
    },
    {
      id: 'mapa.subdim.d1.q1.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — P1 opción D',
      defaultValue: 'Puedo desconectar relativamente rápido.',
      fieldType: 'short',
    },
    {
      id: 'mapa.subdim.d1.q2.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — Pregunta 2',
      defaultValue: 'Ante un imprevisto importante (un email urgente, una crisis en el equipo), ¿qué nota tu cuerpo primero?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Respuesta al estrés agudo.',
    },
    {
      id: 'mapa.subdim.d1.q2.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — P2 opción A',
      defaultValue: 'Taquicardia, opresión en el pecho, dificultad para respirar',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d1.q2.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — P2 opción B',
      defaultValue: 'Tensión muscular intensa (mandíbula, hombros, estómago)',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d1.q2.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — P2 opción C',
      defaultValue: 'Aceleración mental pero sin sensaciones físicas intensas',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d1.q2.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Regulación Nerviosa — P2 opción D',
      defaultValue: 'Alerta pero sin reacción corporal desproporcionada',
      fieldType: 'medium',
    },

    // ── D2: Calidad de Sueño ────────────────────────────────────────────
    {
      id: 'mapa.subdim.d2.intro',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — intro',
      defaultValue: 'Tu calidad de sueño tiene 3 subdimensiones que revelan dónde exactamente se rompe tu descanso:',
      fieldType: 'medium',
      hint: 'Texto introductorio antes de las preguntas de Calidad de Sueño.',
    },
    {
      id: 'mapa.subdim.d2.q1.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — Pregunta 1',
      defaultValue: '¿Qué haces habitualmente en la última hora antes de dormir?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Conciliación.',
    },
    {
      id: 'mapa.subdim.d2.q1.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — P1 opción A',
      defaultValue: 'Trabajo, emails o pantallas hasta el último minuto',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d2.q1.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — P1 opción B',
      defaultValue: 'Intento desconectar pero acabo mirando el móvil',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d2.q1.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — P1 opción C',
      defaultValue: 'Tengo una rutina de desconexión pero no siempre la cumplo',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d2.q1.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — P1 opción D',
      defaultValue: 'Tengo una rutina de desconexión que respeto consistentemente',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d2.q2.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — Pregunta 2',
      defaultValue: '¿Cómo te sientes los primeros 30 minutos después de despertar?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Calidad restaurativa.',
    },
    {
      id: 'mapa.subdim.d2.q2.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — P2 opción A',
      defaultValue: 'Como si no hubiera dormido — agotamiento profundo',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d2.q2.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — P2 opción B',
      defaultValue: 'Pesadez, necesito cafeína para funcionar',
      fieldType: 'short',
    },
    {
      id: 'mapa.subdim.d2.q2.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — P2 opción C',
      defaultValue: 'Algo de lentitud pero funcional en 15-20 minutos',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d2.q2.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Calidad de Sueño — P2 opción D',
      defaultValue: 'Descansado y con energía clara',
      fieldType: 'short',
    },

    // ── D3: Claridad Cognitiva ──────────────────────────────────────────
    {
      id: 'mapa.subdim.d3.intro',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — intro',
      defaultValue: 'Tu claridad cognitiva tiene 3 subdimensiones que explican dónde exactamente se nubla tu mente:',
      fieldType: 'medium',
      hint: 'Texto introductorio antes de las preguntas de Claridad Cognitiva.',
    },
    {
      id: 'mapa.subdim.d3.q1.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — Pregunta 1',
      defaultValue: 'Después de una reunión intensa o una tarea que requiere mucha concentración, ¿cómo responde tu mente?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Foco sostenido.',
    },
    {
      id: 'mapa.subdim.d3.q1.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — P1 opción A',
      defaultValue: 'Quedo completamente agotado — no puedo hacer nada más exigente ese día',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d3.q1.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — P1 opción B',
      defaultValue: 'Necesito al menos 1-2 horas para volver a pensar con claridad',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d3.q1.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — P1 opción C',
      defaultValue: 'Unos 20-30 minutos de pausa y puedo retomar',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d3.q1.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — P1 opción D',
      defaultValue: 'Me recupero rápido y puedo encadenar tareas exigentes',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d3.q2.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — Pregunta 2',
      defaultValue: '¿Cuándo fue la última vez que tuviste una idea creativa o una solución inesperada a un problema?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Capacidad de decisión.',
    },
    {
      id: 'mapa.subdim.d3.q2.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — P2 opción A',
      defaultValue: 'No lo recuerdo — mi mente solo ejecuta, no crea',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d3.q2.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — P2 opción B',
      defaultValue: 'Hace semanas o meses — antes me pasaba más',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d3.q2.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — P2 opción C',
      defaultValue: 'De vez en cuando, normalmente cuando estoy relajado',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d3.q2.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Claridad Cognitiva — P2 opción D',
      defaultValue: 'Con frecuencia — mi mente conecta ideas con facilidad',
      fieldType: 'medium',
    },

    // ── D4: Equilibrio Emocional ────────────────────────────────────────
    {
      id: 'mapa.subdim.d4.intro',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — intro',
      defaultValue: 'Tu equilibrio emocional tiene 3 subdimensiones que revelan el patrón exacto de tu desregulación:',
      fieldType: 'medium',
      hint: 'Texto introductorio antes de las preguntas de Equilibrio Emocional.',
    },
    {
      id: 'mapa.subdim.d4.q1.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — Pregunta 1',
      defaultValue: '¿Puedes identificar qué emoción concreta estás sintiendo mientras la sientes?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Reactividad.',
    },
    {
      id: 'mapa.subdim.d4.q1.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — P1 opción A',
      defaultValue: 'Normalmente solo noto "malestar general" sin poder especificar',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d4.q1.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — P1 opción B',
      defaultValue: 'A veces, pero suelo darme cuenta después — no en tiempo real',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d4.q1.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — P1 opción C',
      defaultValue: 'Casi siempre puedo nombrar lo que siento en el momento',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d4.q1.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — P1 opción D',
      defaultValue: 'Sí, y eso me ayuda a gestionarla antes de que escale',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d4.q2.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — Pregunta 2',
      defaultValue: 'Después de un conflicto o una situación emocionalmente intensa, ¿cuánto tardas en volver a tu estado normal?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Rango emocional.',
    },
    {
      id: 'mapa.subdim.d4.q2.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — P2 opción A',
      defaultValue: 'Horas o incluso días — la emoción me secuestra',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d4.q2.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — P2 opción B',
      defaultValue: 'Varias horas, con pensamientos repetitivos sobre lo ocurrido',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d4.q2.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — P2 opción C',
      defaultValue: 'Una hora aproximadamente, aunque me queda algo de tensión residual',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d4.q2.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Equilibrio Emocional — P2 opción D',
      defaultValue: 'Relativamente rápido — proceso y sigo adelante',
      fieldType: 'medium',
    },

    // ── D5: Alegría de Vivir ────────────────────────────────────────────
    {
      id: 'mapa.subdim.d5.intro',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — intro',
      defaultValue: 'Tu alegría de vivir tiene 3 subdimensiones que revelan qué capa necesita restaurarse primero:',
      fieldType: 'medium',
      hint: 'Texto introductorio antes de las preguntas de Alegría de Vivir.',
    },
    {
      id: 'mapa.subdim.d5.q1.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — Pregunta 1',
      defaultValue: 'Cuando piensas en los próximos 6 meses de tu vida, ¿qué sientes?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Capacidad de placer.',
    },
    {
      id: 'mapa.subdim.d5.q1.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — P1 opción A',
      defaultValue: 'Agotamiento anticipado — más de lo mismo o peor',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d5.q1.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — P1 opción B',
      defaultValue: 'Incertidumbre y algo de temor',
      fieldType: 'short',
    },
    {
      id: 'mapa.subdim.d5.q1.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — P1 opción C',
      defaultValue: 'Neutro — ni ilusión ni temor particular',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d5.q1.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — P1 opción D',
      defaultValue: 'Curiosidad o ilusión por algo concreto',
      fieldType: 'short',
    },
    {
      id: 'mapa.subdim.d5.q2.text',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — Pregunta 2',
      defaultValue: '¿Qué describe mejor tu relación actual con las personas cercanas?',
      fieldType: 'medium',
      hint: 'Afecta la subdimensión: Conexión con otros.',
    },
    {
      id: 'mapa.subdim.d5.q2.optA',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — P2 opción A',
      defaultValue: 'Aislamiento — no tengo energía para nadie',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d5.q2.optB',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — P2 opción B',
      defaultValue: 'Cumplo pero sin disfrutar — es una obligación más',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d5.q2.optC',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — P2 opción C',
      defaultValue: 'Disfruto a veces pero me cuesta iniciar el contacto',
      fieldType: 'medium',
    },
    {
      id: 'mapa.subdim.d5.q2.optD',
      section: 'mapa',
      subsection: 'subdimensions',
      label: 'Alegría de Vivir — P2 opción D',
      defaultValue: 'Mantengo conexiones que me nutren',
      fieldType: 'short',
    },
  ]
}
