'use client'

/**
 * HubAlerts — "Lo que necesitas saber" section.
 *
 * Displays up to 5 narrative alerts generated by profile-intelligence.
 * Each alert has an icon, title, body (clinical narrative), and optional CTA.
 */

import Link from 'next/link'

interface Alert {
  icon: string
  title: string
  body: string
  action?: { label: string; href: string }
  priority: number
  profileColor?: string
}

interface HubAlertsProps {
  alerts: Alert[] | null
  loading: boolean
}

// ── Skeleton ────────────────────────────────────────────────────────────────

function SkeletonAlert() {
  return (
    <div
      style={{
        background: 'var(--color-bg-tertiary)',
        border: 'var(--border-subtle)',
        borderRadius: 'var(--radius-lg)',
        borderLeft: '3px solid var(--color-bg-secondary)',
        padding: 'var(--space-5)',
      }}
    >
      <div
        style={{
          width: '70%',
          height: '14px',
          borderRadius: 'var(--radius-sm)',
          background: 'var(--color-bg-secondary)',
          marginBottom: 'var(--space-3)',
          animation: 'hubPulse 1.5s ease-in-out infinite',
        }}
      />
      <div
        style={{
          width: '100%',
          height: '14px',
          borderRadius: 'var(--radius-sm)',
          background: 'var(--color-bg-secondary)',
          marginBottom: 'var(--space-2)',
          animation: 'hubPulse 1.5s ease-in-out infinite',
          animationDelay: '0.15s',
        }}
      />
      <div
        style={{
          width: '85%',
          height: '14px',
          borderRadius: 'var(--radius-sm)',
          background: 'var(--color-bg-secondary)',
          animation: 'hubPulse 1.5s ease-in-out infinite',
          animationDelay: '0.3s',
        }}
      />
    </div>
  )
}

// ── Component ───────────────────────────────────────────────────────────────

export default function HubAlerts({ alerts, loading }: HubAlertsProps) {
  return (
    <section>
      {/* Section header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 'var(--space-3)',
          marginBottom: 'var(--space-5)',
        }}
      >
        <h2
          style={{
            fontFamily: 'var(--font-host-grotesk)',
            fontSize: 'var(--text-h4)',
            fontWeight: 700,
            color: 'var(--color-text-primary)',
            margin: 0,
          }}
        >
          Lo que necesitas saber
        </h2>
        <div
          style={{
            flex: 1,
            height: '1px',
            background: 'var(--color-surface-subtle)',
          }}
        />
      </div>

      {/* Loading state */}
      {loading && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
          <SkeletonAlert />
          <SkeletonAlert />
          <SkeletonAlert />
        </div>
      )}

      {/* Empty state */}
      {!loading && alerts && alerts.length === 0 && (
        <div
          style={{
            background: 'var(--color-bg-tertiary)',
            border: 'var(--border-subtle)',
            borderRadius: 'var(--radius-lg)',
            padding: 'var(--space-8)',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 'var(--space-3)',
          }}
        >
          <div
            style={{
              width: '48px',
              height: '48px',
              borderRadius: '50%',
              background: 'rgba(61, 154, 95, 0.1)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: '24px',
            }}
          >
            ✓
          </div>
          <p
            style={{
              fontFamily: 'var(--font-host-grotesk)',
              fontSize: 'var(--text-body)',
              color: 'var(--color-text-secondary)',
              textAlign: 'center',
              margin: 0,
            }}
          >
            Todo en orden. No hay alertas que requieran tu atención.
          </p>
        </div>
      )}

      {/* Alerts list */}
      {!loading && alerts && alerts.length > 0 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
          {alerts.map((alert, i) => (
            <div
              key={i}
              style={{
                background: 'var(--color-bg-tertiary)',
                border: 'var(--border-subtle)',
                borderRadius: 'var(--radius-lg)',
                borderLeft: `3px solid ${alert.profileColor ?? 'var(--color-accent)'}`,
                padding: 'var(--space-5)',
              }}
            >
              {/* Title row */}
              <div
                style={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: 'var(--space-3)',
                  marginBottom: 'var(--space-3)',
                }}
              >
                <span style={{ fontSize: '18px', lineHeight: 1.3, flexShrink: 0 }}>
                  {alert.icon}
                </span>
                <p
                  style={{
                    fontFamily: 'var(--font-host-grotesk)',
                    fontSize: 'var(--text-body)',
                    fontWeight: 600,
                    color: 'var(--color-text-primary)',
                    margin: 0,
                    lineHeight: 1.4,
                  }}
                >
                  {alert.title}
                </p>
              </div>

              {/* Body */}
              <p
                style={{
                  fontFamily: 'var(--font-host-grotesk)',
                  fontSize: 'var(--text-body-sm)',
                  color: 'var(--color-text-secondary)',
                  lineHeight: 1.6,
                  margin: 0,
                  marginLeft: 'calc(18px + var(--space-3))',
                }}
              >
                {alert.body}
              </p>

              {/* CTA */}
              {alert.action && (
                <Link
                  href={alert.action.href}
                  style={{
                    display: 'inline-block',
                    marginTop: 'var(--space-3)',
                    marginLeft: 'calc(18px + var(--space-3))',
                    fontFamily: 'var(--font-host-grotesk)',
                    fontSize: '13px',
                    fontWeight: 500,
                    color: 'var(--color-accent)',
                    textDecoration: 'none',
                  }}
                >
                  {alert.action.label} →
                </Link>
              )}
            </div>
          ))}
        </div>
      )}
    </section>
  )
}
